---
# Maximum of 6 disks
snapraid_parity_disks:
  - name: p1
    mount: /mnt/diskp
snapraid_content_disks:
  - /mnt/disk1
  - /mnt/disk2
snapraid_data_disks:
  - name: d1
    mount: /mnt/disk1
  - name: d2
    mount: /mnt/disk2
  - name: d3
    mount: /mnt/disk3
snapraid_exclude_hidden_files: false
snapraid_exclude_files:
  - "*.unrecoverable"
  - /tmp/
  - /lost+found/
