---
kibana_version: "5.x"

# Kibana is served by a back end server. This controls which port to use.
kibana_port: 5601
# The host to bind the server to.
kibana_host: "0.0.0.0"
# If you are running kibana behind a proxy, and want to mount it at a path,
# specify that path here. The basePath can't end in a slash.
kibana_basepath:

kibana_elasticsearch_url: "http://localhost:9200"
